name : "Meu Primeiro Workflow de CI"
on:
    push:
    branches: [ "master" ]
    workflow_dispatch:
    
    
jobs:

primeiro-job:
runs-on: ubuntu-latest

steps:
      - name: Imprime uma mensagem de boas-vindas
        run: echo "Iniciando meu primeiro job!"
      - name: Mostra o diretório de trabalho
        run: pwd
      - name: Lista os arquivos no diretório home
        run: ls ~ -a